# Generated by Django 6.0.2 on 2026-02-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_firestation_latitude_firestation_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firestation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='firestation',
            name='longitude',
        ),
    ]
