# Generated by Django 6.0.2 on 2026-02-28 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_quizresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FireStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_incidents', models.IntegerField(default=0)),
                ('lives_saved', models.IntegerField(default=0)),
                ('properties_protected', models.IntegerField(default=0)),
                ('avg_response_time', models.DecimalField(decimal_places=2, help_text='In minutes', max_digits=5)),
                ('electrical_fires', models.IntegerField(default=0)),
                ('cooking_fires', models.IntegerField(default=0)),
                ('smoking_fires', models.IntegerField(default=0)),
                ('other_fires', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fire Statistics',
                'ordering': ['-year'],
            },
        ),
    ]
