# Generated by Django 6.0.2 on 2026-03-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_faq_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('fire_marshal', 'Fire Marshal'), ('senior_fire_officer', 'Senior Fire Officer'), ('fire_officer', 'Fire Officer'), ('firefighter', 'Firefighter')], default='firefighter', max_length=30)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fire_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='user.firestation')),
            ],
            options={
                'ordering': ['rank', 'last_name'],
            },
        ),
    ]
