# Generated by Django 6.0.2 on 2026-03-20 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_stationpersonnel_middle_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_dispatched', models.DateTimeField(blank=True, null=True)),
                ('time_arrived', models.DateTimeField(blank=True, null=True)),
                ('equipment_used', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personnel_deployed', models.ManyToManyField(blank=True, related_name='response_logs', to='user.stationpersonnel')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_log', to='user.emergencyreport')),
            ],
        ),
    ]
