# Generated by Django 6.0.2 on 2026-03-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_feedback_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='alarm_level',
            field=models.CharField(blank=True, choices=[('1st', '1st Alarm'), ('2nd', '2nd Alarm'), ('3rd', '3rd Alarm'), ('4th', '4th Alarm'), ('5th', '5th Alarm'), ('task_force_alpha', 'Task Force Alpha'), ('task_force_bravo', 'Task Force Bravo'), ('task_force_charlie', 'Task Force Charlie'), ('task_force_delta', 'Task Force Delta'), ('general_alarm', 'General Alarm')], max_length=20, null=True),
        ),
    ]
