# Generated by Django 6.0.2 on 2026-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_emergencyreport_alarm_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
