# Generated by Django 6.0.2 on 2026-03-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_quizresult_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
