# Generated by Django 6.0.2 on 2026-04-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_userprofile_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fire_hose', 'Fire Hose'), ('nozzle', 'Nozzle'), ('fire_hydrant', 'Fire Hydrant'), ('fire_extinguisher', 'Fire Extinguisher'), ('fire_pump', 'Fire Pump'), ('foam_system', 'Foam System'), ('ladder', 'Ladder (Extension & Aerial)'), ('hydraulic_cutter', 'Hydraulic Cutter/Spreader (Jaws of Life)'), ('axe_halligan', 'Axe & Halligan Tool'), ('rope_harness', 'Rope & Harness'), ('crowbar', 'Crowbar'), ('turnout_gear', 'Fire-Resistant Suit (Turnout Gear)'), ('helmet', 'Helmet'), ('gloves_boots', 'Gloves & Boots'), ('scba', 'SCBA (Self-Contained Breathing Apparatus)'), ('flashlight', 'Flashlight'), ('thermal_camera', 'Thermal Imaging Camera'), ('gas_detector', 'Gas Detector'), ('radio', 'Radio'), ('first_aid_kit', 'First Aid Kit'), ('aed', 'AED (Automated External Defibrillator)'), ('stretcher', 'Stretcher'), ('oxygen_tank', 'Oxygen Tank'), ('ventilation_fan', 'Ventilation Fan'), ('generator', 'Generator'), ('chainsaw', 'Chainsaw')], max_length=100)),
                ('category', models.CharField(choices=[('suppression', 'Fire Suppression Equipment'), ('rescue', 'Rescue Equipment'), ('ppe', 'Personal Protective Equipment'), ('detection', 'Search & Detection Tools'), ('medical', 'Medical Equipment'), ('ventilation', 'Ventilation & Support Tools')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair')], default='operational', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fire_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='user.firestation')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
