# Generated by Django 6.0.2 on 2026-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_stationequipment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationequipment',
            unique_together={('fire_station', 'name')},
        ),
        migrations.AddField(
            model_name='stationequipment',
            name='damaged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationequipment',
            name='operational',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationequipment',
            name='under_repair',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='stationequipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stationequipment',
            name='status',
        ),
    ]
