# Generated by Django 6.0.2 on 2026-04-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_stationequipment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair')], default='operational', max_length=20)),
                ('water_level', models.CharField(choices=[('full', 'Full'), ('half', 'Half'), ('empty', 'Empty')], default='full', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fire_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_trucks', to='user.firestation')),
            ],
            options={
                'ordering': ['truck_number'],
            },
        ),
    ]
