# Generated by Django 6.0.2 on 2026-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_firetruck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
