# Generated by Django 6.0.2 on 2026-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_userstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_stories/'),
        ),
    ]
