# Generated by Django 6.0.2 on 2026-04-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_userstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='image',
            field=models.ImageField(upload_to='user_stories/'),
        ),
    ]
