# Generated by Django 6.0.2 on 2026-04-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_userstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationpersonnel',
            name='status',
            field=models.CharField(choices=[('on_duty', 'On Duty'), ('on_leave', 'On Leave'), ('absent', 'Absent'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
